# -*- coding: utf-8 -*-
"""tweetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10MeaNsE4IyN5Kxtq8r4AHQSkTMwWt2xG
"""


#!pip install m3inference

import twint
import nest_asyncio
import pandas as pd
from IPython.display import HTML
import requests
import matplotlib.pyplot as plt
nest_asyncio.apply()


def tw_data(topic,limit):

  t=twint.Config()
  t.Search=topic
  t.Store_object = True
  #t.Near="Egypt"
  t.Limit=limit
  t.Since = '2020-11-01'
  t.Until = '2021-05-01'
  t.Popular_tweets=True
  t.Hide_output = True
  t.Store_csv = True
  t.Output = "Data"
  twint.run.Search(t)
  df = pd.read_csv('Data/tweets.csv' , sep = ",")
  #df.info()
  print("Done Collect the Data")
  return df

df=tw_data("KIA",1000)

#visualization of count of tweetes per date
plt.figure()
plt.plot(df['date'].value_counts())
plt.show()

##visualization by Age
##plt.figure()
##plt.bar(df['Age'].unique(),df['Age'].value_counts()[df['Age'].unique()])
##plt.show()
##
##visualization by gender
##plt.figure()
##plt.bar(df['Gender'].unique(),df['Gender'].value_counts()[df['Gender'].unique()])
##plt.show()
